### ISSUE TITLE
parser doesn't support bare raise statements

### ISSUE THREAD

**Issue by diego-ponce** [heavenshell/py-doq#100]
Python allows [a `raise` statement without expressions](https://docs.python.org/2/reference/simple_stmts.html?highlight=raise#grammar-token-raise-stmt), which raises the last exception in the active scope. In these cases `raise` will not have children and `parse_defs` will fail when appending exceptions at line 103 of `parser.py`. 

Minimal code to reproduce the error:
```
# bare_raise.py
def foo():
    try:
        12/0 # force an exception
    except:
        raise
```
```
cat bare_raise.py | python -m doq.cli
```
output 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rumple/py-doq/doq/cli.py", line 373, in <module>
    main()
  File "/home/rumple/py-doq/doq/cli.py", line 363, in main
    ret = run(args)
  File "/home/rumple/py-doq/doq/cli.py", line 215, in run
    docstrings = generate_docstrings(
  File "/home/rumple/py-doq/doq/cli.py", line 114, in generate_docstrings
    signatures = parse(
  File "/home/rumple/py-doq/doq/parser.py", line 185, in parse
    results += parse_defs(
  File "/home/rumple/py-doq/doq/parser.py", line 103, in parse_defs
    exceptions.append(e.children[1].get_first_leaf().get_code().strip())
AttributeError: 'Keyword' object has no attribute 'children'
```

**Comment by heavenshell** [comment]
@diego-ponce 
Release as 0.9.1
https://pypi.org/project/doq/0.9.1/

Thank you for your contribution!

**Comment by diego-ponce** [comment]
Thank you!

That was super fun - let me know if you have other features or work you are hoping to do with this package. I find it very helpful.

Diego
